apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trying-keda-svc-monitor
  labels:
    app: trying-keda
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app: trying-keda