apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-app-scaled-object
spec:
  scaleTargetRef:
    kind: Deployment
    name: trying-keda-deployment
  pollingInterval: 10 # default 30 seconds
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://10.96.180.178:9090
        metricName: http_requests_total
        threshold: '2'
        query: sum(rate(http_requests_total[1m]))
